# Generated by Django 4.1.4 on 2023-02-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(max_length=12)),
                ('c_email', models.EmailField(max_length=100)),
                ('c_name', models.CharField(max_length=100)),
                ('c_address', models.CharField(max_length=100)),
                ('c_phoneNo', models.CharField(max_length=10)),
            ],
        ),
    ]
