# Generated by Django 4.1.4 on 2023-02-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_canteen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(max_length=12)),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.FloatField(max_length=5)),
            ],
        ),
    ]
