# Generated by Django 4.1.4 on 2023-02-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='c_feedback',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
