# Generated by Django 4.1.4 on 2023-03-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_viewprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredCntnOwners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('cname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('cpwd', models.CharField(max_length=100)),
            ],
        ),
    ]
