# Generated by Django 4.1.4 on 2023-03-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_canteen_c_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('rating', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='viewprofile',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
