# Generated by Django 4.1.4 on 2023-03-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_feedback_alter_viewprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.CharField(max_length=5),
        ),
    ]
