# Generated by Django 4.1.4 on 2023-04-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_feedback_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesUpdated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(max_length=12)),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.FloatField(max_length=5)),
                ('item_status', models.CharField(max_length=10)),
            ],
        ),
    ]
