# Generated by Django 4.1.4 on 2023-04-06 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_categoriesupdated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeredcntnowners',
            old_name='cname',
            new_name='c_id',
        ),
    ]
