# Generated by Django 4.1.4 on 2023-04-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_rename_cname_registeredcntnowners_c_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredcntnowners',
            name='c_id',
            field=models.IntegerField(),
        ),
    ]
