# Generated by Django 4.1.4 on 2023-04-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_alter_registeredcntnowners_c_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackCanteenId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.IntegerField()),
            ],
        ),
    ]
