# Generated by Django 4.1.4 on 2023-04-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_trackcanteenid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('im', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
